### ISSUE TITLE
PostgreSQL 15.3

### ISSUE THREAD

**Issue by Davidnadejdin** [TablePlus/DBngin#104]
Please update to PostgreSQL 15.3. Because the old version of PostgreSQL 15.1 trying to load extensions(Postgis in my case) which depends on llibtiff.5.dylib which has been updated to libtiff.6.dylib

**Comment by Davidnadejdin** [comment]
@huyphams please 🥲

**Comment by patryk-smc** [comment]
That would be great @huyphams

**Comment by njwest** [comment]
PostGIS should work if you downgrade to 14.3

**Comment by igorkasyanchuk** [comment]
does anyone have a solution for this error?

**Comment by huyphams** [comment]
Hmm are you using pg 15 @igorkasyanchuk ?

**Comment by igorkasyanchuk** [comment]
tried with PG16, 15 and 14. Only works with 14.

```
Caused by:
PG::UndefinedFile: ERROR:  could not load library "/Users/Shared/DBngin/postgresql/15.1/lib/postgis-3.so": dlopen(/Users/Shared/DBngin/postgresql/15.1/lib/postgis-3.so, 0x000A): Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib (PG::UndefinedFile)
  Referenced from: <6AAD9711-1CB0-3BCD-BCE9-F990AC56DBCD> /Users/Shared/DBngin/postgresql/15.1/lib/libproj.25.dylib
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/usr/local/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)
/Users/igorkasyanchuk/projects/megakadastr/db/schema.rb:16:in `block in <main>'
/Users/igorkasyanchuk/projects/megakadastr/db/schema.rb:13:in `<main>'
Tasks: TOP => db:schema:load
```
