### ISSUE TITLE
Add Postgis support

### ISSUE THREAD

**Issue by igorkasyanchuk** [TablePlus/DBngin#159]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): Posgres 16.4

2. DBngin build number and platform (Ex: build 70 on MacOS):

7.3

4. macOS/Windows version (Ex: macOS Sonoma):

3,2 GHz 6-Core Intel Core i7
MacOS 15.1 (24B83)

5. The steps to reproduce this issue:

ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not load library "/Users/Shared/DBngin/postgresql/16.4/lib/postgis-3.dylib": dlopen(/Users/Shared/DBngin/postgresql/16.4/lib/postgis-3.dylib, 0x000A): tried: '/Users/Shared/DBngin/postgresql/16.4/lib/postgis-3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/Shared/DBngin/postgresql/16.4/lib/postgis-3.dylib' (no such file), '/Users/Shared/DBngin/postgresql/16.4/lib/postgis-3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')) (ActiveRecord::StatementInvalid)
/Users/igorkasyanchuk/projects/megakadastr/db/schema.rb:16:in `block in <main>'
/Users/igorkasyanchuk/projects/megakadastr/db/schema.rb:13:in `<main>'

Please add support for Postgis for Postgres v16 or v17 (both doesn't work for me)

**Comment by 0xdevalias** [comment]
@igorkasyanchuk This answer from another issue may point you in the right direction, it's installing `pgvector`, but I assume it would be similar for `postgis`:

> ```
> export PATH=/Users/Shared/DBngin/postgresql/14.3/bin:$PATH
> git clone https://github.com/pgvector/pgvector.git
> cd pgvector
> make && make install
> ```
> 
> _Originally posted by @batnieluyo in https://github.com/TablePlus/DBngin/issues/113#issuecomment-1925012964_

**Comment by K2412** [comment]
installing it locally worked for me : https://postgis.net/documentation/getting_started/
